pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'dev', url: 'https://github.com/TerekhovaAnastasia/car_tuning.git'
            }
        }

        stage('Run Tests') {
            steps {
                powershell '''
                    $python = "C:\\Users\\Катя\\PycharmProjects\\PythonProject1\\.venv\\Scripts\\python.exe"
                    cd "$env:WORKSPACE\\my_1st_client_server"
                    & $python manage.py test
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                powershell '''
                    cd "$env:WORKSPACE\\my_1st_client_server"
                    docker build -t car-tuning-app .
                '''
            }
        }
    }

    post {
        success {
            echo 'All tests passed! Docker image built!'
        }
        failure {
            echo 'Tests failed or Docker build failed.'
        }
    }
}